name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      # - name: Install dependencies
      #   run: yarn install --frozen-lockfile

      # TODO: Add integration UI tests
      # - name: Run integration UI tests
      #   run: yarn test:integration